AWSTemplateFormatVersion: "2010-09-09"
Description: "SSM creation to automate encrypting new Amazon Linux AMIs"
Parameters:
  AMIeEC2InstanceProfile:
    Description: "AMI Encryption EC2 instance profile name"
    Type: "String"
  AMIeSSMRoleARN:
    Description: "AMI Encryption SSM service role ARN"
    Type: "String"
Outputs:
  AmazonLinuxSSMAutomationDocument:
    Value: !Ref "AmazonLinuxSSMAutomationDocument"
Resources:
  AmazonLinuxSSMAutomationDocument:
    Type: "AWS::SSM::Document"
    Properties:
      DocumentType: "Automation"
      Content:
        schemaVersion: "0.3"
        description: "Automation Document to Encrypt Amazon Linux AMIs."
        assumeRole: "{{AutomationAssumeRoleARN}}"
        parameters:
          InstanceProfileName:
            type: "String"
            description: "EC2 IAM profile that is allowed to perform RunCommand."
            default: !Ref "AMIeEC2InstanceProfile"
          AutomationAssumeRoleARN:
            type: "String"
            description: "Role under which to execute this automation."
            default: !Ref "AMIeSSMRoleARN"
          AmazonLinux2SourceAmiId:
            type: "String"
            description: "Source Amazon Linux 2 AMI ID."
        mainSteps:
        - name: "createEncryptedCopy"
          action: "aws:copyImage"
          maxAttempts: 3
          onFailure: "Abort"
          inputs:
              SourceImageId: "{{AmazonLinux2SourceAmiId}}"
              SourceRegion: "us-east-1"
              ImageName: "Encrypted - Amazon Linux 2 - Sourced from {{AmazonLinux2SourceAmiId}} on {{global:DATE}}"
              ImageDescription: "Encrypted - Amazon Linux 2 - Sourced from {{AmazonLinux2SourceAmiId}} on {{global:DATE}}"
              Encrypted: true
        - name: "createTags"
          action: "aws:createTags"
          maxAttempts: 3
          onFailure: "Continue"
          inputs:
              ResourceType: "EC2"
              ResourceIds:
              - "{{createEncryptedCopy.ImageId}}"
              Tags:
              - Key: "cc_exception"
                Value: "ami-90-day"
        outputs:
        - createEncryptedCopy.ImageId
