AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates lambda function to trigger SSM automation and allows it to be invoked by SNS"
Parameters:
  AmazonLinuxNewAMITopicARN:
    Description: "Amazon Linux New AMI SNS topic ARN"
    Type: "String"
    Default: "arn:aws:sns:us-east-1:137112412989:amazon-linux-ami-updates"
  AMIeLambdaRoleARN:
    Description: "Lambda role ARN"
    Type: "String"
  AMIeSSMRoleARN:
    Description: "SSM role ARN"
    Type: "String"
  AmazonLinuxSSMAutomationDocument:
    Description: "Automation document name"
    Type: "String"
Outputs:
    AmazonLinux2SSMLambdaARN:
      Value: !GetAtt "AmazonLinux2SSMLambda.Arn"
Resources:
  AmazonLinux2SSMLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.lambda_handler"
      Runtime: "python2.7"
      Role: !Ref "AMIeLambdaRoleARN"
      Timeout: 300
      Environment:
        Variables:
          DocumentName: !Ref "AmazonLinuxSSMAutomationDocument"
          AutomationAssumeRoleARN: !Ref "AMIeSSMRoleARN"
      Code:
        ZipFile: |
          import os
          import boto3
          import logging
          import operator
          from datetime import datetime
          def lambda_handler(event, context):
            logger = logging.getLogger(__name__)
            logger.addHandler(logging.StreamHandler())
            logger.setLevel(logging.INFO)
            ec2_client = boto3.client('ec2')
            ssm_client = boto3.client('ssm')
            response = ec2_client.describe_images(Owners=['amazon'], Filters=[{'Name': 'name', 'Values': ['amzn2-ami-hvm-????.??.??.*-x86_64-gp2']}])
            images = [{'ImageId':image['ImageId'], 'CreationDate': datetime.strptime(image['CreationDate'], '%Y-%m-%dT%H:%M:%S.%fZ')} for image in response['Images']]
            images = sorted(images, reverse=True, key=operator.itemgetter('CreationDate'))
            ami_id = images[0]['ImageId']
            logger.info("ami-id: {}".format(ami_id))
            response = ssm_client.start_automation_execution(DocumentName=os.environ['DocumentName'],
              Parameters={'AmazonLinux2SourceAmiId': [ami_id,], 'AutomationAssumeRoleARN': [os.environ['AutomationAssumeRoleARN'],]}
            )
            logger.info(response)
  SSMLambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt "AmazonLinux2SSMLambda.Arn"
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref "AmazonLinuxNewAMITopicARN"
