AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to automate AMI patching process"
Outputs:
  SSMLambdaARN:
    Value: !GetAtt "SSMLambda.Outputs.SSMLambdaARN"
Parameters:
  NewAMITopicARN:
    Description: "New AMI SNS topic ARN"
    Type: "String"
#    Default: "arn:aws:sns:us-east-1:137112412989:amazon-linux-ami-updates" # Amazon Linux
#    Default: "arn:aws:sns:us-east-1:801119661308:ec2-windows-ami-update"   # Windows
    Default: "arn:aws:sns:us-east-1:829829645734:SNSLinux" #created for testing
  S3BucketName:
    Type: "String"
    MinLength: 3
    Default: "ami-encryption-automagic" # My temporary S3 bucket that contains all the ymls
Resources:
  AMIeSSMRoles:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/roles.yml"
  SSMDocument:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/ssm.yml"
      Parameters:
        AMIeEC2InstanceProfile: !GetAtt "AMIeSSMRoles.Outputs.AMIeEC2InstanceProfile"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
  SSMLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/lambda.yml"
      Parameters:
        NewAMITopicARN: !Ref "NewAMITopicARN"
        AMIeLambdaRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeLambdaRoleARN"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
        SSMAutomationDocument: !GetAtt "SSMDocument.Outputs.SSMAutomationDocument"
