AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to automate AMI patching process"
Outputs:
  AmazonLinux2SSMLambdaARN:
    Value: !GetAtt "AmazonLinux2SSMLambda.Outputs.AmazonLinux2SSMLambdaARN"
  Windows2012R2BaseSSMLambdaARN:
    Value: !GetAtt "Windows2012R2BaseSSMLambda.Outputs.Windows2012R2BaseSSMLambdaARN"
  Windows2016FullBaseSSMLambdaARN:
    Value: !GetAtt "Windows2016FullBaseSSMLambda.Outputs.Windows2016FullBaseSSMLambdaARN"
  Windows2016SQL2017STDSSMLambdaARN:
    Value: !GetAtt "Windows2016SQL2017STDSSMLambda.Outputs.Windows2016SQL2017STDSSMLambdaARN"
Parameters:
  AmazonLinuxNewAMITopicARN:
    Description: "Amazon Linux New AMI SNS topic ARN"
    Type: "String"
#    Default: "arn:aws:sns:us-east-1:137112412989:amazon-linux-ami-updates" # Amazon Linux
    Default: "arn:aws:sns:us-east-1:829829645734:SNSLinux" #created for testing
  WindowsNewAMITopicARN:
    Description: "Windows New AMI SNS topic ARN"
    Type: "String"
#    Default: "arn:aws:sns:us-east-1:801119661308:ec2-windows-ami-update"   # Windows
    Default: "arn:aws:sns:us-east-1:829829645734:SNSWindows" #created for testing
  S3BucketName:
    Description: "S3 Bucket that contains the YMLs"
    Type: "String"
    MinLength: 3
    Default: "ami-encryption-automagic" # My temporary S3 bucket that contains all the ymls
Resources:
  AMIeSSMRoles:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/roles.yml"
  AmazonLinuxSSMDocument:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/AmazonLinuxssm.yml"
      Parameters:
        AMIeEC2InstanceProfile: !GetAtt "AMIeSSMRoles.Outputs.AMIeEC2InstanceProfile"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
  AmazonLinux2SSMLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/AmazonLinux2lambda.yml"
      Parameters:
        AmazonLinuxNewAMITopicARN: !Ref "AmazonLinuxNewAMITopicARN"
        AMIeLambdaRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeLambdaRoleARN"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
        AmazonLinuxSSMAutomationDocument: !GetAtt "AmazonLinuxSSMDocument.Outputs.AmazonLinuxSSMAutomationDocument"
  Windows2012R2BaseSSMDocument:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/Windows2012R2Basessm.yml"
      Parameters:
        AMIeEC2InstanceProfile: !GetAtt "AMIeSSMRoles.Outputs.AMIeEC2InstanceProfile"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
  Windows2012R2BaseSSMLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/Windows2012R2Baselambda.yml"
      Parameters:
        WindowsNewAMITopicARN: !Ref "WindowsNewAMITopicARN"
        AMIeLambdaRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeLambdaRoleARN"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
        Windows2012R2BaseSSMAutomationDocument: !GetAtt "Windows2012R2BaseSSMDocument.Outputs.Windows2012R2BaseSSMAutomationDocument"
  Windows2016FullBaseSSMDocument:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/Windows2016FullBasessm.yml"
      Parameters:
        AMIeEC2InstanceProfile: !GetAtt "AMIeSSMRoles.Outputs.AMIeEC2InstanceProfile"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
  Windows2016FullBaseSSMLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/Windows2016FullBaselambda.yml"
      Parameters:
        WindowsNewAMITopicARN: !Ref "WindowsNewAMITopicARN"
        AMIeLambdaRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeLambdaRoleARN"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
        Windows2016FullBaseSSMAutomationDocument: !GetAtt "Windows2016FullBaseSSMDocument.Outputs.Windows2016FullBaseSSMAutomationDocument"
  Windows2016SQL2017STDSSMDocument:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/Windows2016SQL2017STDssm.yml"
      Parameters:
        AMIeEC2InstanceProfile: !GetAtt "AMIeSSMRoles.Outputs.AMIeEC2InstanceProfile"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
  Windows2016SQL2017STDSSMLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/Windows2016SQL2017STDlambda.yml"
      Parameters:
        WindowsNewAMITopicARN: !Ref "WindowsNewAMITopicARN"
        AMIeLambdaRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeLambdaRoleARN"
        AMIeSSMRoleARN: !GetAtt "AMIeSSMRoles.Outputs.AMIeSSMRoleARN"
        Windows2016SQL2017STDSSMAutomationDocument: !GetAtt "Windows2016SQL2017STDSSMDocument.Outputs.Windows2016SQL2017STDSSMAutomationDocument"
