AWSTemplateFormatVersion: "2010-09-09"
Description: "Subscribes previously created Lambda functions to related AMI update SNS topic. RUN ONLY IN us-east-1 REGION"
Parameters:
  AmazonLinux2SSMLambdaARN:
    Type: "String"
  Windows2012R2BaseSSMLambdaARN:
    Type: "String"
  Windows2016FullBaseSSMLambdaARN:
    Type: "String"
  Windows2016SQL2017STDSSMLambdaARN:
    Type: "String"
Resources:
  AmazonLinux2AMITopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref "AmazonLinux2SSMLambdaARN"
      Protocol: lambda
      TopicArn: "arn:aws:sns:us-east-1:137112412989:amazon-linux-ami-updates"
  Windows2012R2BaseAMITopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref "Windows2012R2BaseSSMLambdaARN"
      Protocol: lambda
      TopicArn: "arn:aws:sns:us-east-1:801119661308:ec2-windows-ami-update"
  Windows2016FullBaseAMITopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref "Windows2016FullBaseSSMLambdaARN"
      Protocol: lambda
      TopicArn: "arn:aws:sns:us-east-1:801119661308:ec2-windows-ami-update"
  Windows2016SQL2017STDAMITopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref "Windows2016SQL2017STDSSMLambdaARN"
      Protocol: lambda
      TopicArn: "arn:aws:sns:us-east-1:801119661308:ec2-windows-ami-update"
