AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to automate encrypting new AMIs process"
Parameters:
  EC2InstanceProfile:
    Description: "EC2 instance profile name"
    Type: "String"
  SSMRoleARN:
    Description: "SSM service role ARN"
    Type: "String"
Outputs:
  SSMAutomationDocument:
    Value: !Ref "SSMAutomationDocument"
Resources:
  SSMAutomationDocument:
    Type: "AWS::SSM::Document"
    Properties:
      DocumentType: "Automation"
      Content:
        schemaVersion: "0.3"
        description: "Automation Document to Encrypt Amazon Linux 2 AMI."
        assumeRole: "{{AutomationAssumeRoleARN}}"
        parameters:
          InstanceProfileName:
            type: "String"
            description: "EC2 IAM profile that is allowed to perform RunCommand."
            default: !Ref "EC2InstanceProfile"
          AutomationAssumeRoleARN:
            type: "String"
            description: "Role under which to execute this automation."
            default: !Ref "SSMRoleARN"
          SourceAmiId:
            type: "String"
            description: "Source Amazon Linux 2 AMI ID."
        mainSteps:
        - name: "createEncryptedCopy"
          action: "aws:copyImage"
          maxAttempts: 3
          onFailure: "Abort"
          inputs:
            SourceImageId: "{{SourceAmiId}}"
            SourceRegion: "us-east-1"
            ImageName: "Encrypted Amazon Linux 2 - Sourced from {{SourceAmiId}} on {{global:DATE}}"
            Encrypted: true
        - name: "updateSsmParam"
          action: "aws:invokeLambdaFunction"
          timeoutSeconds: 15
          maxAttempts: 1
          onFailure: "Abort"
          inputs:
            FunctionName: "parameterStoreUpdater"
            Payload: "{\"parameterName\":\"latestEncryptedLinuxAMI\", \"parameterValue\":\"{{createEncryptedCopy.ImageId}}\"}"
        outputs:
        - createEncryptedCopy.ImageId
