AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to automate encrypting new AMIs process"
Parameters:
  SSMRoleARN:
    Description: "SSM service role ARN"
    Type: "String"
Outputs:
  SSMAutomationDocument:
    Value: !Ref "SSMAutomationDocument"
Resources:
  SSMAutomationDocument:
    Type: "AWS::SSM::Document"
    Properties:
      DocumentType: "Automation"
      Content:
        schemaVersion: "0.3"
        description: "Automation Document to Encrypt Linux AMI."
        assumeRole: "{{AutomationAssumeRoleARN}}"
        parameters:
          InstanceProfileName:
            type: "String"
            description: "EC2 IAM profile that is allowed to perform RunCommand."
            default: !Ref "EC2InstanceProfile"
          AutomationAssumeRoleARN:
            type: "String"
            description: "Role under which to execute this automation."
            default: !Ref "SSMRoleARN"
          SourceAmiId:
            type: "String"
            description: "The source Amazon Machine Image ID."
        mainSteps:
        - name: "createEncryptedCopy"
          action: "aws:copyImage"
          maxAttempts: 3
          onFailure: "Abort"
          inputs:
            ImageId: "{{SourceAmiId}}"
            SourceRegion: "us-east-1"
            ImageName: "Encrypted Copy of {{ SourceAmiId }}"
            Encrypted: true
        outputs:
        - createEncryptedCopy.ImageId
        - createEncryptedCopy.ImageName
